/** Demo grocery catalog when Base44 CatalogProduct is empty or unavailable */
export const DEMO_GROCERY_PRODUCTS = [
  // خضروات
  {
    id: 'demo-grocery-1',
    name: 'طماطم طازجة',
    brand: 'محلي',
    size: '1 كيلو',
    category: 'خضروات',
    unit_type: 'كيلو',
    price: 4.5,
    description: 'طماطم حمراء طازجة من المزارع المحلية',
    image_url: 'https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=300&q=80',
    is_available: true,
    is_active: true,
    is_popular: true,
  },
  {
    id: 'demo-grocery-2',
    name: 'خيار',
    brand: 'محلي',
    size: '500 جرام',
    category: 'خضروات',
    unit_type: 'كيس',
    price: 3,
    description: 'خيار مقرمش مناسب للسلطات',
    image_url: 'https://images.unsplash.com/photo-1449300369323-0211648d8478?w=300&q=80',
    is_available: true,
    is_active: true,
    is_popular: false,
  },
  {
    id: 'demo-grocery-3',
    name: 'بطاطس',
    brand: 'محلي',
    size: '2 كيلو',
    category: 'خضروات',
    unit_type: 'كيس',
    price: 5.5,
    description: 'بطاطس نظيفة جاهزة للطبخ',
    image_url: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=300&q=80',
    is_available: true,
    is_active: true,
    is_popular: false,
  },
  // ألبان ومنتجات
  {
    id: 'demo-grocery-4',
    name: 'حليب المراعي',
    brand: 'المراعي',
    size: '1 لتر',
    category: 'ألبان ومنتجات',
    unit_type: 'علبة كرتون',
    price: 6.5,
    description: 'حليب طازج كامل الدسم',
    image_url: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=300&q=80',
    is_available: true,
    is_active: true,
    is_popular: true,
  },
  {
    id: 'demo-grocery-5',
    name: 'جبنة كيري',
    brand: 'كيري',
    size: '8 قطع',
    category: 'ألبان ومنتجات',
    unit_type: 'علبة',
    price: 8,
    description: 'جبنة طرية للفطور والسندويتشات',
    image_url: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=300&q=80',
    is_available: true,
    is_active: true,
    is_popular: false,
  },
  {
    id: 'demo-grocery-6',
    name: 'لبن رايب',
    brand: 'المراعي',
    size: '180 مل',
    category: 'ألبان ومنتجات',
    unit_type: 'علبة',
    price: 3.5,
    description: 'لبن رايب منعش',
    image_url: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?w=300&q=80',
    is_available: true,
    is_active: true,
    is_popular: false,
  },
  // مياه ومشروبات
  {
    id: 'demo-grocery-7',
    name: 'ماء هنا',
    brand: 'هنا',
    size: '330 مل',
    category: 'مياه ومشروبات',
    unit_type: 'زجاجة',
    price: 1,
    description: 'مياه معدنية نقية',
    image_url: 'https://images.unsplash.com/photo-1548839140-29a7492991f9?w=300&q=80',
    is_available: true,
    is_active: true,
    is_popular: true,
  },
  {
    id: 'demo-grocery-8',
    name: 'عصير برتقال',
    brand: 'المراعي',
    size: '1 لتر',
    category: 'مياه ومشروبات',
    unit_type: 'علبة كرتون',
    price: 4,
    description: 'عصير برتقال طبيعي 100%',
    image_url: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=300&q=80',
    is_available: true,
    is_active: true,
    is_popular: false,
  },
  {
    id: 'demo-grocery-9',
    name: 'بيبسي',
    brand: 'بيبسي',
    size: '330 مل',
    category: 'مياه ومشروبات',
    unit_type: 'علبة',
    price: 2.5,
    description: 'مشروب غازي بارد',
    image_url: 'https://images.unsplash.com/photo-1629203432180-71e9b18d855c?w=300&q=80',
    is_available: true,
    is_active: true,
    is_popular: false,
  },
  // سناكس وشوكولاتة
  {
    id: 'demo-grocery-10',
    name: 'شيبس ليز',
    brand: 'ليز',
    size: '170 جرام',
    category: 'سناكس وشوكولاتة',
    unit_type: 'كيس',
    price: 5,
    description: 'بطاطس مقرمشة بنكهة الملح',
    image_url: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=300&q=80',
    is_available: true,
    is_active: true,
    is_popular: true,
  },
  {
    id: 'demo-grocery-11',
    name: 'كيت كات',
    brand: 'نستlé',
    size: '41.5 جرام',
    category: 'سناكس وشوكولاتة',
    unit_type: 'حبة',
    price: 3,
    description: 'شوكولاتة مقرمشة بالويفر',
    image_url: 'https://images.unsplash.com/photo-1606312619070-d48b4cbc1225?w=300&q=80',
    is_available: true,
    is_active: true,
    is_popular: false,
  },
  {
    id: 'demo-grocery-12',
    name: 'بسكوت أوريو',
    brand: 'أوريو',
    size: '154 جرام',
    category: 'سناكس وشوكولاتة',
    unit_type: 'علبة',
    price: 6,
    description: 'بسكوت بالكريمة والشوكولاتة',
    image_url: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=300&q=80',
    is_available: true,
    is_active: true,
    is_popular: false,
  },
  // منظفات
  {
    id: 'demo-grocery-13',
    name: 'فيبي منظف أرضيات',
    brand: 'فيبي',
    size: '1.8 لتر',
    category: 'منظفات',
    unit_type: 'زجاجة',
    price: 12,
    description: 'منظف أرضيات برائحة اللافندر',
    image_url: 'https://images.unsplash.com/photo-1583947215250-46b6592a5e1e?w=300&q=80',
    is_available: true,
    is_active: true,
    is_popular: false,
  },
  {
    id: 'demo-grocery-14',
    name: 'صابون داي',
    brand: 'P&G',
    size: '800 مل',
    category: 'منظفات',
    unit_type: 'زجاجة',
    price: 8.5,
    description: 'صابون سائل للأطباق والأواني',
    image_url: 'https://images.unsplash.com/photo-1610557892470-55d9a57c3b41?w=300&q=80',
    is_available: true,
    is_active: true,
    is_popular: false,
  },
  {
    id: 'demo-grocery-15',
    name: 'مناديل معطرة',
    brand: 'فاين',
    size: '200 منديل',
    category: 'منظفات',
    unit_type: 'علبة',
    price: 15,
    description: 'مناديل معطرة للاستخدام اليومي',
    image_url: 'https://images.unsplash.com/photo-1584438784894-089d6a62b8ba?w=300&q=80',
    is_available: true,
    is_active: true,
    is_popular: false,
  },
];
